baseURL: "https://example.com"
languageCode: "en-us"
title: "The Hinged"
pygmentsstyle: 'monokai'
# Novela settings
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
  







